// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCvC_LpBx-pQgdC-o6zHsmQLWjTFeKcU',
    appId: '1:413599396828:web:47a93bb4bf83365fcc9519',
    messagingSenderId: '413599396828',
    projectId: 'assigment-firebase-b08d3',
    authDomain: 'assigment-firebase-b08d3.firebaseapp.com',
    storageBucket: 'assigment-firebase-b08d3.firebasestorage.app',
    measurementId: 'G-GFVDDV5T56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ixJ8UMoMHqdhBT6wP41gfmYyue4GA7o',
    appId: '1:413599396828:android:8a6fb17c3f8610d5cc9519',
    messagingSenderId: '413599396828',
    projectId: 'assigment-firebase-b08d3',
    storageBucket: 'assigment-firebase-b08d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCyZ67cUPEywFLbpgfkhAUiFcQcB7qXGE',
    appId: '1:413599396828:ios:fe8f318bc70233a0cc9519',
    messagingSenderId: '413599396828',
    projectId: 'assigment-firebase-b08d3',
    storageBucket: 'assigment-firebase-b08d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCyZ67cUPEywFLbpgfkhAUiFcQcB7qXGE',
    appId: '1:413599396828:ios:fe8f318bc70233a0cc9519',
    messagingSenderId: '413599396828',
    projectId: 'assigment-firebase-b08d3',
    storageBucket: 'assigment-firebase-b08d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKCvC_LpBx-pQgdC-o6zHsmQLWjTFeKcU',
    appId: '1:413599396828:web:15b50388f48beaf7cc9519',
    messagingSenderId: '413599396828',
    projectId: 'assigment-firebase-b08d3',
    authDomain: 'assigment-firebase-b08d3.firebaseapp.com',
    storageBucket: 'assigment-firebase-b08d3.firebasestorage.app',
    measurementId: 'G-MHB3G7MYWJ',
  );
}
